// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const ConsumerSecretsAttributesSchema = z.object({
  id: z.string().uuid(),
  consumerSecretId: z.string().uuid(),
  key: z.string(),
  encryptedValue: zodBuffer.nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TConsumerSecretsAttributes = z.infer<typeof ConsumerSecretsAttributesSchema>;
export type TConsumerSecretsAttributesInsert = Omit<z.input<typeof ConsumerSecretsAttributesSchema>, TImmutableDBKeys>;
export type TConsumerSecretsAttributesUpdate = Partial<
  Omit<z.input<typeof ConsumerSecretsAttributesSchema>, TImmutableDBKeys>
>;
